#!/usr/bin/env bash

set -euo pipefail

# Detect platform
OS="$(uname -s)"
BREWFILE_FILE="$HOME/.Brewfile"

# Check if brew is installed
if ! command -v brew >/dev/null 2>&1; then
	echo "[+] Installing Homebrew..."

	NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

	# Set up brew path
	if [[ "$OS" == "Linux" ]]; then
		eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
	elif [[ "$OS" == "Darwin" ]]; then
		eval "$(/opt/homebrew/bin/brew shellenv)"
	fi
fi

echo "[+] Homebrew detected: $(brew --version | head -n1)"

# Use appropriate Brewfile
if [[ "$OS" == "Darwin" ]]; then
	echo "[+] Running brew bundle using Brewfile.macos..."
	brew bundle --file="$BREWFILE_FILE"

elif [[ "$OS" == "Linux" ]]; then
	echo "[+] Running brew bundle using Brewfile.linux..."
	brew bundle --file="$BREWFILE_FILE"

else
	echo "[-] Unsupported OS: $OS"
	exit 1
fi

echo "[+] Done."
